
package vista;


public class SesionAdminOClientes extends javax.swing.JFrame {

    
    public SesionAdminOClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnInicioAdmin = new javax.swing.JButton();
        btnInicioCliente = new javax.swing.JButton();
        lblPromocion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 204, 255));
        lblTitulo.setText("StudioGamer");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnInicioAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnInicioAdmin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInicioAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioAdmin.setText("Inicio de Administracion");
        btnInicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btnInicioCliente.setBackground(new java.awt.Color(0, 204, 204));
        btnInicioCliente.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInicioCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioCliente.setText("Inicio de cliente");
        btnInicioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblPromocion.setBackground(new java.awt.Color(255, 255, 0));
        lblPromocion.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        lblPromocion.setForeground(new java.awt.Color(255, 0, 0));
        lblPromocion.setText("Descuento en tu primera compra");
        getContentPane().add(lblPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/R.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 130, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4768220eda2bdf16308f85bc566d46f7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioClienteActionPerformed
        abrirClientes();
    }//GEN-LAST:event_btnInicioClienteActionPerformed

    private void btnInicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAdminActionPerformed
         abrirLogin();
    }//GEN-LAST:event_btnInicioAdminActionPerformed

    /**
     * Método para abrir la ventana de Clientes.
     */
    private void abrirClientes() {
        Clientes clientes = new Clientes(); // Asegúrate de que la clase Clientes esté creada
        clientes.setVisible(true);
        this.dispose(); // Cierra la ventana actual si es necesario
    }

    /**
     * Método para abrir la ventana de Login.
     */
    private void abrirLogin() {
        Login login = new Login(); // Asegúrate de que la clase Login esté creada
        login.setVisible(true);
        this.dispose(); // Cierra la ventana actual si es necesario
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionAdminOClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionAdminOClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionAdminOClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionAdminOClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionAdminOClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioAdmin;
    private javax.swing.JButton btnInicioCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPromocion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
